# Basics
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'
set -g mouse on

# PowerKit plugin
set -g @plugin 'fabioluciano/tmux-powerkit'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
#set -g @plugin 'b0o/tmux-autoreload
#set -g @plugin 'sainnhe/tmux-fzf'
#set -g @plugin 'wfxr/tmux-fzf-url'

# Basic configuration
#set -g @powerkit_plugins "datetime,battery,cpu,memory,git,hostname"
set -g @powerkit_plugins "ssh,hostname"
# Catppuccin - Mocha variant
#set -g @powerkit_theme "catppuccin"
#set -g @powerkit_theme_variant "mocha"
# Tokyo Night - Night variant
set -g @powerkit_theme "tokyo-night"
set -g @powerkit_theme_variant "night"
# Dracula
#set -g @powerkit_theme "dracula"
#set -g @powerkit_theme_variant "dark"

# git
set -g @powerkit_plugin_git_icon ""
set -g @powerkit_plugin_git_show_branch "true"
set -g @powerkit_plugin_git_show_files "true"
set -g @powerkit_plugin_git_max_length "30"

# Choose your separator style
set -g @powerkit_separator_style "rounded"  # rounded or normal, flame, pixel, honeycomb

# Enable spacing between elements
#set -g @powerkit_elements_spacing "both"

# Customize update interval
set -g @powerkit_status_interval "5"

# Make it transparent
set -g @powerkit_transparent "true"

# Restore session
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

#set -g pane-active-border-style 'fg=magenta,bg=default'
#set -g pane-border-style 'fg=brightblack,bg=default'

#set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
#set -g @fzf-url-history-limit '2000'

# Initialize TPM (keep at bottom)
run '~/.config/tmux/plugins/tpm/tpm'

run '~/.config/tmux/plugins/tmux-autoreload/tmux-autoreload.tmux'
